apiVersion: v1
kind: ConfigMap
metadata:
  name: blockverse-config
  namespace: blockverse
data:
  # Database Configurations
  DB_HOST: "blockverse-production-mysql.ch2uwg2a80dc.ap-south-1.rds.amazonaws.com"
  DB_PORT: "3306"
  DB_NAME: "blockverse"
  DB_USER: "dbadmin"
  
  # Redis Configurations
  SPRING_DATA_REDIS_HOST: "blockverse-redis"
  SPRING_DATA_REDIS_PORT: "6379"
  
  # Kafka Configurations
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "blockverse-kafka:9092"
  
  # AWS configurations
  AWS_REGION: "ap-south-1"
  AWS_S3_BUCKET: "blockverse-production-assets-bucket-yjpr1x6d"
  
  # Frontend configurations
  NEXT_PUBLIC_API_BASE_URL: "http://65.0.171.134"
  NEXT_PUBLIC_WS_URL: "ws://65.0.171.134/ws"
  SPRING_PROFILES_ACTIVE: "prod"
